# Generated by Django 5.2.3 on 2025-06-17 11:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('staffs', '0002_initial'),
        ('students', '0001_initial'),
        ('subjects', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='creditlimit',
            name='semester',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='subjects.semester'),
        ),
        migrations.AddField(
            model_name='major',
            name='department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='students.department'),
        ),
        migrations.AddField(
            model_name='student',
            name='account',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='student',
            name='department',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='students.department'),
        ),
        migrations.AddField(
            model_name='student',
            name='major',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='students.major'),
        ),
        migrations.AddField(
            model_name='device',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='students.student'),
        ),
        migrations.AddField(
            model_name='creditlimit',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='students.student'),
        ),
        migrations.AddField(
            model_name='studentsubject',
            name='semester',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='subjects.semester'),
        ),
        migrations.AddField(
            model_name='studentsubject',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='students.student'),
        ),
        migrations.AddField(
            model_name='studentsubject',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='subjects.subject'),
        ),
        migrations.AddField(
            model_name='subjectregistrationrequest',
            name='approved_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='staffs.staff'),
        ),
        migrations.AddField(
            model_name='subjectregistrationrequest',
            name='semester',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='subjects.semester'),
        ),
        migrations.AddField(
            model_name='subjectregistrationrequest',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='students.student'),
        ),
        migrations.AddField(
            model_name='subjectregistrationrequest',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='subjects.subject'),
        ),
        migrations.AddIndex(
            model_name='major',
            index=models.Index(fields=['department_id'], name='majors_departm_f1969e_idx'),
        ),
        migrations.AddIndex(
            model_name='student',
            index=models.Index(fields=['department'], name='students_departm_bebd12_idx'),
        ),
        migrations.AddIndex(
            model_name='student',
            index=models.Index(fields=['major'], name='students_major_i_cd8e25_idx'),
        ),
        migrations.AddIndex(
            model_name='student',
            index=models.Index(fields=['account'], name='students_account_a3374b_idx'),
        ),
        migrations.AddIndex(
            model_name='device',
            index=models.Index(fields=['student_id'], name='devices_student_8a6a7c_idx'),
        ),
        migrations.AddIndex(
            model_name='creditlimit',
            index=models.Index(fields=['student_id'], name='credit_limi_student_7381b1_idx'),
        ),
        migrations.AddIndex(
            model_name='creditlimit',
            index=models.Index(fields=['semester_id'], name='credit_limi_semeste_a50b25_idx'),
        ),
        migrations.AddIndex(
            model_name='studentsubject',
            index=models.Index(fields=['student_id'], name='student_sub_student_083e8e_idx'),
        ),
        migrations.AddIndex(
            model_name='studentsubject',
            index=models.Index(fields=['subject_id'], name='student_sub_subject_29581e_idx'),
        ),
        migrations.AddIndex(
            model_name='studentsubject',
            index=models.Index(fields=['semester_id'], name='student_sub_semeste_502c44_idx'),
        ),
        migrations.AddIndex(
            model_name='subjectregistrationrequest',
            index=models.Index(fields=['student_id'], name='subject_reg_student_38f821_idx'),
        ),
        migrations.AddIndex(
            model_name='subjectregistrationrequest',
            index=models.Index(fields=['subject_id'], name='subject_reg_subject_dded0c_idx'),
        ),
        migrations.AddIndex(
            model_name='subjectregistrationrequest',
            index=models.Index(fields=['semester_id'], name='subject_reg_semeste_85448b_idx'),
        ),
        migrations.AddIndex(
            model_name='subjectregistrationrequest',
            index=models.Index(fields=['approved_by_id'], name='subject_reg_approve_c57cc4_idx'),
        ),
    ]
