# Generated by Django 5.2.3 on 2025-08-19 08:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0002_initial'),
        ('subjects', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='studentsubject',
            name='subject_registration_request',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='students.subjectregistrationrequest'),
        ),
        migrations.AddIndex(
            model_name='studentsubject',
            index=models.Index(fields=['subject_registration_request_id'], name='student_sub_subject_936dac_idx'),
        ),
    ]
