# Generated by Django 5.2.3 on 2025-06-24 05:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0003_classstudent_registered_by_account_and_more'),
        ('lecturers', '0002_lecturer_lecturer_code'),
        ('students', '0002_initial'),
        ('subjects', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SubjectClass',
            fields=[
                ('subject_class_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Subject Class',
                'verbose_name_plural': 'Subject Classes',
                'db_table': 'subject_classes',
                'managed': True,
            },
        ),
        migrations.AddField(
            model_name='studentsubject',
            name='registered_by_account',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='studentsubject',
            index=models.Index(fields=['registered_by_account_id'], name='student_sub_registe_17c846_idx'),
        ),
        migrations.AddField(
            model_name='subjectclass',
            name='class_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='classes.class'),
        ),
        migrations.AddField(
            model_name='subjectclass',
            name='lecturer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lecturers.lecturer'),
        ),
        migrations.AddField(
            model_name='subjectclass',
            name='semester',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='subjects.semester'),
        ),
        migrations.AddField(
            model_name='subjectclass',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='subjects.subject'),
        ),
        migrations.AddIndex(
            model_name='subjectclass',
            index=models.Index(fields=['subject_id'], name='subject_cla_subject_d1721f_idx'),
        ),
        migrations.AddIndex(
            model_name='subjectclass',
            index=models.Index(fields=['class_id'], name='subject_cla_class_i_46d91d_idx'),
        ),
        migrations.AddIndex(
            model_name='subjectclass',
            index=models.Index(fields=['lecturer_id'], name='subject_cla_lecture_aaf44e_idx'),
        ),
        migrations.AddIndex(
            model_name='subjectclass',
            index=models.Index(fields=['semester_id'], name='subject_cla_semeste_ec1af0_idx'),
        ),
    ]
