# Generated by Django 5.2.3 on 2025-11-30 12:24

from django.db import migrations

def update_sessions(apps, schema_editor):
    Subject = apps.get_model('subjects', 'Subject')
    for subject in Subject.objects.all():
        if subject.total_credits == 2:
            subject.sessions_per_class = 2
        else:
            subject.sessions_per_class = 3
        subject.save()
        
class Migration(migrations.Migration):

    dependencies = [
        ('students', '0003_init_triggers'),
    ]

    operations = [
        migrations.RunPython(update_sessions),
    ]