# Generated by Django 5.2.3 on 2025-08-27 06:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staffs', '0003_remove_staff_avatar_url'),
        ('students', '0004_alter_creditlimit_semester'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subjectregistrationrequest',
            name='approved_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='staffs.staff'),
        ),
        migrations.AlterField(
            model_name='subjectregistrationrequest',
            name='status',
            field=models.CharField(default='pending', max_length=20),
        ),
    ]
