# Generated by Django 5.2.3 on 2025-08-27 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0005_alter_subjectregistrationrequest_approved_by_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subjectregistrationrequest',
            name='status',
            field=models.CharField(default='pending'),
        ),
    ]
