# Generated by Django 5.2.3 on 2025-08-28 05:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0007_alter_subjectregistrationrequest_approved_by'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='studentsubject',
            name='student_sub_registe_17c846_idx',
        ),
        migrations.RemoveField(
            model_name='studentsubject',
            name='registered_by_account',
        ),
    ]
