# Generated by Django 5.2.3 on 2025-06-26 18:55

import classes.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('rooms', '0001_initial'),
        ('students', '0002_initial'),
        ('subjects', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Class',
            fields=[
                ('class_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('class_name', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(default='1', max_length=1)),
                ('class_code', models.CharField(default=classes.models.generate_random_code, max_length=20, unique=True)),
                ('academic_year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='subjects.academicyear')),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='students.department')),
            ],
            options={
                'verbose_name': 'Class',
                'verbose_name_plural': 'Classes',
                'db_table': 'classes',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='ClassStudent',
            fields=[
                ('class_student_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('is_active', models.CharField(default='0', max_length=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('registration_status', models.CharField(default='auto', max_length=20)),
                ('class_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='classes.class')),
                ('registered_by_account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='students.student')),
            ],
            options={
                'verbose_name': 'Class Student',
                'verbose_name_plural': 'Class Students',
                'db_table': 'class_students',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('schedule_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField()),
                ('repeat_weekly', models.CharField(max_length=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('latitude', models.DecimalField(decimal_places=5, max_digits=10)),
                ('longitude', models.DecimalField(decimal_places=5, max_digits=10)),
                ('lesson_type', models.CharField(max_length=50)),
                ('day_of_week', models.IntegerField(null=True)),
                ('class_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='classes.class')),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rooms.room')),
                ('slot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='subjects.lessonslot')),
                ('subject_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='subjects.subject')),
            ],
            options={
                'verbose_name': 'Schedule',
                'verbose_name_plural': 'Schedules',
                'db_table': 'schedules',
                'managed': True,
            },
        ),
        migrations.AddIndex(
            model_name='class',
            index=models.Index(fields=['department_id'], name='classes_departm_98bb5e_idx'),
        ),
        migrations.AddIndex(
            model_name='class',
            index=models.Index(fields=['academic_year_id'], name='classes_academi_c56e9f_idx'),
        ),
        migrations.AddIndex(
            model_name='classstudent',
            index=models.Index(fields=['class_id'], name='class_stude_class_i_05f053_idx'),
        ),
        migrations.AddIndex(
            model_name='classstudent',
            index=models.Index(fields=['student_id'], name='class_stude_student_a2eaf8_idx'),
        ),
        migrations.AddIndex(
            model_name='classstudent',
            index=models.Index(fields=['registered_by_account_id'], name='class_stude_registe_3e129b_idx'),
        ),
        migrations.AddIndex(
            model_name='schedule',
            index=models.Index(fields=['class_id'], name='schedules_class_i_bf9668_idx'),
        ),
        migrations.AddIndex(
            model_name='schedule',
            index=models.Index(fields=['subject_id'], name='schedules_subject_3d2967_idx'),
        ),
        migrations.AddIndex(
            model_name='schedule',
            index=models.Index(fields=['room_id'], name='schedules_room_id_3a02e7_idx'),
        ),
        migrations.AddIndex(
            model_name='schedule',
            index=models.Index(fields=['slot_id'], name='schedules_slot_id_481994_idx'),
        ),
    ]
