# Generated by Django 5.2.3 on 2025-09-12 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='schedule',
            name='status',
            field=models.CharField(default='1', max_length=1, null=True),
        ),
    ]
