# Generated by Django 5.2.3 on 2025-06-17 12:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0001_initial'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='class',
            name='classes_room_id_d48178_idx',
        ),
        migrations.RemoveField(
            model_name='class',
            name='room',
        ),
    ]
