# Generated by Django 5.2.3 on 2025-09-13 01:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0002_schedule_status'),
        ('students', '0008_remove_studentsubject_student_sub_registe_17c846_idx_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='classstudent',
            options={'verbose_name': 'Class Student', 'verbose_name_plural': 'Class Students'},
        ),
        migrations.AlterField(
            model_name='classstudent',
            name='class_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='class_students', to='classes.class'),
        ),
        migrations.AlterField(
            model_name='classstudent',
            name='registered_by_account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registered_classes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='classstudent',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='class_students', to='students.student'),
        ),
    ]
