# Generated by Django 5.2.3 on 2025-06-24 05:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0002_remove_class_classes_room_id_d48178_idx_and_more'),
        ('students', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='classstudent',
            name='registered_by_account',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='classstudent',
            index=models.Index(fields=['registered_by_account_id'], name='class_stude_registe_3e129b_idx'),
        ),
    ]
