# Generated by Django 5.2.3 on 2025-06-24 06:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0003_classstudent_registered_by_account_and_more'),
        ('rooms', '0001_initial'),
        ('subjects', '0002_lessonslot'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='schedule',
            name='schedules_shift_i_b93976_idx',
        ),
        migrations.RemoveField(
            model_name='schedule',
            name='shift',
        ),
        migrations.AddField(
            model_name='schedule',
            name='day_of_week',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='schedule',
            name='lesson_type',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='schedule',
            name='slot',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='subjects.lessonslot'),
        ),
        migrations.AddIndex(
            model_name='schedule',
            index=models.Index(fields=['slot_id'], name='schedules_slot_id_481994_idx'),
        ),
    ]
