# Generated by Django 5.2.3 on 2025-11-30 13:51

import helper.generate_random_code
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('contact_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('contact_code', models.UUIDField(default=helper.generate_random_code.generate_random_code, unique=True)),
                ('fullname', models.CharField(blank=True, max_length=255, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('phone_number', models.CharField(blank=True, max_length=10, null=True)),
                ('type_person_contact', models.CharField(choices=[('ADMIN', 'Admin'), ('LECTURER', 'Lecturer'), ('STUDENT', 'Student')], max_length=10)),
                ('to_person_id', models.PositiveIntegerField()),
                ('message', models.TextField()),
                ('response', models.TextField(blank=True, null=True)),
                ('status', models.CharField(choices=[('UNREAD', 'Unread'), ('READ', 'Read'), ('REPLIED', 'Replied')], default='UNREAD', max_length=10)),
                ('status_response', models.CharField(choices=[('UNREAD', 'Unread'), ('READ', 'Read'), ('REPLIED', 'Replied')], default='UNREAD', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Contact',
                'verbose_name_plural': 'Contacts',
                'db_table': 'contacts',
                'ordering': ['-created_at'],
            },
        ),
    ]
