# Generated by Django 5.2.3 on 2025-11-30 13:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contact', '0001_initial'),
        ('contenttypes', '0002_remove_content_type_name'),
        ('subjects', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='subject',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='subjects.subject'),
        ),
        migrations.AddField(
            model_name='contact',
            name='to_person_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='to_person_type', to='contenttypes.contenttype'),
        ),
    ]
