# Generated by Django 5.2.3 on 2025-06-26 18:55

import accounts.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Role',
            fields=[
                ('role_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('role_name', models.CharField(max_length=50, unique=True)),
                ('role_code', models.CharField(default=accounts.models.generate_random_code, max_length=50, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Role',
                'verbose_name_plural': 'Roles',
                'db_table': 'roles',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Account',
            fields=[
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('account_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('email', models.CharField(max_length=200, unique=True)),
                ('password', models.CharField(max_length=255)),
                ('is_active', models.BooleanField(default=True)),
                ('phone_number', models.CharField(max_length=10, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_login_at', models.DateTimeField(auto_now_add=True)),
                ('avatar_url', models.ImageField(blank=True, null=True, upload_to='avatars/')),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('is_locked', models.BooleanField(default=False)),
                ('is_verified_email', models.BooleanField(default=False)),
                ('user_type', models.CharField(max_length=50)),
                ('is_staff', models.BooleanField(default=False)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.role')),
            ],
            options={
                'verbose_name': 'Account',
                'verbose_name_plural': 'Accounts',
                'db_table': 'accounts',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Permisson',
            fields=[
                ('permission_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('entity_name', models.CharField(max_length=255)),
                ('field_name', models.CharField(max_length=100)),
                ('read', models.CharField(max_length=1)),
                ('insert', models.CharField(max_length=1)),
                ('update', models.CharField(max_length=1)),
                ('delete', models.CharField(max_length=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('account', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.role')),
            ],
            options={
                'verbose_name': 'Permission',
                'verbose_name_plural': 'Permissions',
                'db_table': 'permissions',
                'managed': True,
                'indexes': [models.Index(fields=['role_id'], name='permissions_role_id_a1bd90_idx'), models.Index(fields=['account_id'], name='permissions_account_a6aaba_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='account',
            index=models.Index(fields=['role_id'], name='accounts_role_id_8b4a51_idx'),
        ),
    ]
