# Generated by Django 5.2.3 on 2025-08-19 08:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('staffs', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='staff',
            name='avatar_url',
        ),
    ]
