# Generated by Django 5.2.3 on 2025-06-26 18:56

import django.core.serializers.json
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('log_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('operation', models.CharField(max_length=1)),
                ('old_data', models.JSONField(encoder=django.core.serializers.json.DjangoJSONEncoder)),
                ('new_data', models.JSONField(encoder=django.core.serializers.json.DjangoJSONEncoder)),
                ('changed_at', models.DateTimeField(auto_now_add=True)),
                ('ip_address', models.CharField(max_length=255)),
                ('user_agent', models.CharField(max_length=255)),
                ('record_id', models.CharField(max_length=255)),
                ('entity_id', models.CharField(max_length=255)),
                ('entity_name', models.CharField(max_length=255)),
                ('action_description', models.TextField(null=True)),
                ('changed_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Audit Log',
                'verbose_name_plural': 'Audit Logs',
                'db_table': 'audit_logs',
                'managed': True,
                'indexes': [models.Index(fields=['changed_by'], name='audit_logs_changed_310180_idx')],
            },
        ),
        migrations.CreateModel(
            name='LoginLog',
            fields=[
                ('log_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('login_time', models.TimeField(auto_now=True)),
                ('ip_address', models.CharField(max_length=255)),
                ('user_agent', models.TextField()),
                ('device_info', models.TextField()),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Login Log',
                'verbose_name_plural': 'Login Logs',
                'db_table': 'login_logs',
                'managed': True,
                'indexes': [models.Index(fields=['account_id'], name='login_logs_account_a9fd47_idx')],
            },
        ),
    ]
