# Generated by Django 5.2.3 on 2025-06-16 15:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('lecturers', '0001_initial'),
        ('students', '0002_initial'),
        ('subjects', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LeaveRequest',
            fields=[
                ('leave_request_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('reason', models.TextField()),
                ('from_date', models.DateTimeField(auto_now_add=True)),
                ('to_date', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(max_length=1)),
                ('attachment', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('rejected_reason', models.TextField(null=True)),
                ('reviewed_at', models.DateTimeField(auto_now_add=True)),
                ('approved_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lecturers.lecturer')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='students.student')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='subjects.subject')),
            ],
            options={
                'verbose_name': 'Leave Request',
                'verbose_name_plural': 'Leave Requests',
                'db_table': 'leave_requests',
                'managed': True,
                'indexes': [models.Index(fields=['student_id'], name='leave_reque_student_ac431e_idx'), models.Index(fields=['subject_id'], name='leave_reque_subject_39470c_idx'), models.Index(fields=['approved_by'], name='leave_reque_approve_778c77_idx')],
            },
        ),
    ]
