# Generated by Django 5.2.3 on 2025-09-12 14:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leaves', '0001_initial'),
        ('lecturers', '0004_remove_lecturer_phone_number'),
        ('students', '0008_remove_studentsubject_student_sub_registe_17c846_idx_and_more'),
        ('subjects', '0002_subject_sessions_per_class'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='leaverequest',
            options={'verbose_name': 'Leave Request', 'verbose_name_plural': 'Leave Requests'},
        ),
        migrations.RemoveIndex(
            model_name='leaverequest',
            name='leave_reque_student_ac431e_idx',
        ),
        migrations.RemoveIndex(
            model_name='leaverequest',
            name='leave_reque_subject_39470c_idx',
        ),
        migrations.AddField(
            model_name='leaverequest',
            name='academic_year',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='subjects.academicyear'),
        ),
        migrations.AddField(
            model_name='leaverequest',
            name='semester',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='subjects.semester'),
        ),
        migrations.AddField(
            model_name='leaverequest',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='leaverequest',
            name='approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='lecturers.lecturer'),
        ),
        migrations.AlterField(
            model_name='leaverequest',
            name='attachment',
            field=models.FileField(blank=True, null=True, upload_to='leave_attachments/'),
        ),
        migrations.AlterField(
            model_name='leaverequest',
            name='from_date',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='leaverequest',
            name='rejected_reason',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='leaverequest',
            name='reviewed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='leaverequest',
            name='status',
            field=models.CharField(choices=[('P', 'Pending'), ('A', 'Approved'), ('R', 'Rejected')], default='P', max_length=1),
        ),
        migrations.AlterField(
            model_name='leaverequest',
            name='to_date',
            field=models.DateTimeField(),
        ),
        migrations.AddIndex(
            model_name='leaverequest',
            index=models.Index(fields=['student'], name='leave_reque_student_ac431e_idx'),
        ),
        migrations.AddIndex(
            model_name='leaverequest',
            index=models.Index(fields=['subject'], name='leave_reque_subject_39470c_idx'),
        ),
    ]
