# Generated by Django 5.2.3 on 2025-09-14 11:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leaves', '0002_alter_leaverequest_options_and_more'),
        ('lecturers', '0005_alter_subjectclass_class_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='leaverequest',
            name='to_target',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='targeted_leave_requests', to='lecturers.lecturer'),
        ),
        migrations.AlterField(
            model_name='leaverequest',
            name='approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_leave_requests', to='lecturers.lecturer'),
        ),
    ]
