# Generated by Django 5.2.3 on 2025-06-17 11:59

import django.db.models.deletion
import subjects.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AcademicYear',
            fields=[
                ('academic_year_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('academic_year_name', models.CharField(max_length=255)),
                ('academic_year_code', models.CharField(default=subjects.models.generate_random_code, max_length=20, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Academic Year',
                'verbose_name_plural': 'Academic Years',
                'db_table': 'academic_years',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Shift',
            fields=[
                ('shift_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('shift_name', models.CharField(max_length=255)),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('status', models.CharField(default='1', max_length=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Shift',
                'verbose_name_plural': 'Shifts',
                'db_table': 'shifts',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Semester',
            fields=[
                ('semester_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('semester_code', models.CharField(default=subjects.models.generate_random_code, max_length=20, unique=True)),
                ('semester_name', models.CharField(max_length=255)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('status', models.CharField(default='1', max_length=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('academic_year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='subjects.academicyear')),
            ],
            options={
                'verbose_name': 'Semester',
                'verbose_name_plural': 'Semesters',
                'db_table': 'semesters',
                'managed': True,
                'indexes': [models.Index(fields=['academic_year_id'], name='semesters_academi_47be9a_idx')],
            },
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('subject_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('subject_name', models.CharField(max_length=255)),
                ('status', models.CharField(default='1', max_length=1)),
                ('subject_code', models.CharField(default=subjects.models.generate_random_code, max_length=20, unique=True)),
                ('theoretical_credits', models.IntegerField()),
                ('practical_credits', models.IntegerField()),
                ('total_credits', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('academic_year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='subjects.academicyear')),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='students.department')),
            ],
            options={
                'verbose_name': 'Subject',
                'verbose_name_plural': 'Subjects',
                'db_table': 'subjects',
                'managed': True,
                'indexes': [models.Index(fields=['department_id'], name='subjects_departm_26ad56_idx'), models.Index(fields=['academic_year_id'], name='subjects_academi_6ef194_idx')],
            },
        ),
    ]
