# Generated by Django 5.2.3 on 2025-08-26 01:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subjects', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='subject',
            name='sessions_per_class',
            field=models.IntegerField(null=True),
        ),
    ]
