# Generated by Django 5.2.3 on 2025-06-24 06:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subjects', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LessonSlot',
            fields=[
                ('slot_id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('slot_name', models.CharField(max_length=50)),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('duration_minutes', models.IntegerField()),
                ('shift_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='subjects.shift')),
            ],
            options={
                'verbose_name': 'Lesson Slot',
                'verbose_name_plural': 'Lesson Slots',
                'db_table': 'lesson_slots',
                'managed': True,
                'indexes': [models.Index(fields=['shift_id'], name='lesson_slot_shift_i_109ce3_idx')],
            },
        ),
    ]
