# Generated by Django 5.2.3 on 2025-06-26 18:55

import django.db.models.deletion
import lecturers.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('classes', '0001_initial'),
        ('students', '0002_initial'),
        ('subjects', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Lecturer',
            fields=[
                ('lecturer_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('lecturer_code', models.CharField(default=lecturers.models.generate_random_code, max_length=8, unique=True)),
                ('fullname', models.CharField(max_length=255)),
                ('gender', models.CharField(max_length=1)),
                ('dob', models.DateField()),
                ('avatar_url', models.TextField(null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('account', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='students.department')),
            ],
            options={
                'verbose_name': 'Lecturer',
                'verbose_name_plural': 'Lecturers',
                'db_table': 'lecturers',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='LecturerSubject',
            fields=[
                ('lecturer_subject_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('lecturer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lecturers.lecturer')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='subjects.subject')),
            ],
            options={
                'verbose_name': 'Lecturer Subject',
                'verbose_name_plural': 'Lecturer Subjects',
                'db_table': 'lecturer_subjects',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='SubjectClass',
            fields=[
                ('subject_class_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('class_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='classes.class')),
                ('lecturer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lecturers.lecturer')),
                ('semester', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='subjects.semester')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='subjects.subject')),
            ],
            options={
                'verbose_name': 'Subject Class',
                'verbose_name_plural': 'Subject Classes',
                'db_table': 'subject_classes',
                'managed': True,
            },
        ),
        migrations.AddIndex(
            model_name='lecturer',
            index=models.Index(fields=['account_id'], name='lecturers_account_9bca51_idx'),
        ),
        migrations.AddIndex(
            model_name='lecturer',
            index=models.Index(fields=['department_id'], name='lecturers_departm_77f381_idx'),
        ),
        migrations.AddIndex(
            model_name='lecturersubject',
            index=models.Index(fields=['subject_id'], name='lecturer_su_subject_d130f9_idx'),
        ),
        migrations.AddIndex(
            model_name='lecturersubject',
            index=models.Index(fields=['lecturer_id'], name='lecturer_su_lecture_068b11_idx'),
        ),
        migrations.AddIndex(
            model_name='subjectclass',
            index=models.Index(fields=['subject_id'], name='subject_cla_subject_d1721f_idx'),
        ),
        migrations.AddIndex(
            model_name='subjectclass',
            index=models.Index(fields=['class_id'], name='subject_cla_class_i_46d91d_idx'),
        ),
        migrations.AddIndex(
            model_name='subjectclass',
            index=models.Index(fields=['lecturer_id'], name='subject_cla_lecture_aaf44e_idx'),
        ),
        migrations.AddIndex(
            model_name='subjectclass',
            index=models.Index(fields=['semester_id'], name='subject_cla_semeste_ec1af0_idx'),
        ),
    ]
