# Generated by Django 5.2.3 on 2025-06-27 16:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0001_initial'),
        ('lecturers', '0001_initial'),
        ('subjects', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='subjectclass',
            unique_together={('subject', 'class_id', 'lecturer', 'semester')},
        ),
    ]
