# Generated by Django 5.2.3 on 2025-06-20 05:17

import lecturers.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lecturers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='lecturer',
            name='lecturer_code',
            field=models.CharField(blank=True, default=lecturers.models.generate_random_code, max_length=8, null=True, unique=True),
        ),
    ]
