# Generated by Django 5.2.3 on 2025-08-19 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lecturers', '0002_alter_subjectclass_unique_together'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lecturer',
            name='avatar_url',
        ),
        migrations.AddField(
            model_name='lecturer',
            name='phone_number',
            field=models.CharField(max_length=10, null=True, unique=True),
        ),
    ]
