# Generated by Django 5.2.3 on 2025-08-19 09:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lecturers', '0003_remove_lecturer_avatar_url_lecturer_phone_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lecturer',
            name='phone_number',
        ),
    ]
