# Generated by Django 5.2.3 on 2025-09-13 01:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0003_alter_classstudent_options_and_more'),
        ('lecturers', '0004_remove_lecturer_phone_number'),
        ('subjects', '0002_subject_sessions_per_class'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subjectclass',
            name='class_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subject_classes', to='classes.class'),
        ),
        migrations.AlterField(
            model_name='subjectclass',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subject_classes', to='subjects.subject'),
        ),
    ]
