# Generated by Django 5.2.3 on 2025-09-16 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0002_notification_to_target_alter_notification_created_by_and_more'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='reminder',
            name='reminders_academi_1406d3_idx',
        ),
        migrations.RemoveField(
            model_name='reminder',
            name='academic_year',
        ),
        migrations.AlterField(
            model_name='reminder',
            name='email_notification',
            field=models.CharField(default='1', max_length=1),
        ),
    ]
