# Generated by Django 5.2.3 on 2025-06-17 12:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('classes', '0001_initial'),
        ('lecturers', '0001_initial'),
        ('students', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('attendance_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('status', models.CharField(max_length=1)),
                ('checkin_time', models.TimeField(auto_now_add=True)),
                ('face_image_url', models.TextField()),
                ('verified_by_ai', models.CharField(max_length=1)),
                ('checkin_lat', models.DecimalField(decimal_places=5, max_digits=10)),
                ('checkin_long', models.DecimalField(decimal_places=5, max_digits=10)),
                ('note', models.TextField(null=True)),
                ('attendance_type', models.CharField(max_length=1)),
                ('is_late', models.CharField(max_length=1)),
                ('late_reason', models.TextField(null=True)),
                ('checkin_method', models.CharField(max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('checkin_device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='students.device')),
                ('schedule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='classes.schedule')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='students.student')),
            ],
            options={
                'verbose_name': 'Attendance',
                'verbose_name_plural': 'Attendances',
                'db_table': 'attendances',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='AttendanceVerification',
            fields=[
                ('verification_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('verified_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(default='1', max_length=1)),
                ('note', models.TextField(null=True)),
                ('attendance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='attendance.attendance')),
                ('lecturer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lecturers.lecturer')),
            ],
            options={
                'verbose_name': 'Attendance Verification',
                'verbose_name_plural': 'Attendance Verifications',
                'db_table': 'attendance_verifications',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='FaceRecognitionLog',
            fields=[
                ('face_recognition_log_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('student', models.CharField(max_length=255)),
                ('face_embedding', models.BinaryField()),
                ('face_image_url', models.TextField()),
                ('confidence_score', models.DecimalField(decimal_places=5, max_digits=10)),
                ('note', models.TextField(null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('attendace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='attendance.attendance')),
            ],
            options={
                'verbose_name': 'Face Recognition Log',
                'verbose_name_plural': 'Face Recognition Logs',
                'db_table': 'face_recognition_logs',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='QRCheckin',
            fields=[
                ('qr_checkin_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('qr_code', models.CharField(max_length=255)),
                ('expire_at', models.TimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.CharField(max_length=1)),
                ('usage_count', models.IntegerField()),
                ('max_usage', models.IntegerField()),
                ('radius', models.IntegerField()),
                ('latitude', models.DecimalField(decimal_places=5, max_digits=10)),
                ('longitude', models.DecimalField(decimal_places=5, max_digits=10)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lecturers.lecturer')),
                ('schedule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='classes.schedule')),
                ('used_by_student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='students.student')),
            ],
            options={
                'verbose_name': 'QR Checkin',
                'verbose_name_plural': 'QR Checkins',
                'db_table': 'qr_checkins',
                'managed': True,
            },
        ),
        migrations.AddIndex(
            model_name='attendance',
            index=models.Index(fields=['schedule_id'], name='attendances_schedul_438604_idx'),
        ),
        migrations.AddIndex(
            model_name='attendance',
            index=models.Index(fields=['student_id'], name='attendances_student_57d8b0_idx'),
        ),
        migrations.AddIndex(
            model_name='attendance',
            index=models.Index(fields=['checkin_device_id'], name='attendances_checkin_8a3486_idx'),
        ),
        migrations.AddIndex(
            model_name='attendanceverification',
            index=models.Index(fields=['attendance_id'], name='attendance__attenda_d92bd0_idx'),
        ),
        migrations.AddIndex(
            model_name='attendanceverification',
            index=models.Index(fields=['lecturer_id'], name='attendance__lecture_f2bd07_idx'),
        ),
        migrations.AddIndex(
            model_name='facerecognitionlog',
            index=models.Index(fields=['attendace_id'], name='face_recogn_attenda_8f5bbd_idx'),
        ),
        migrations.AddIndex(
            model_name='qrcheckin',
            index=models.Index(fields=['schedule_id'], name='qr_checkins_schedul_624ce1_idx'),
        ),
        migrations.AddIndex(
            model_name='qrcheckin',
            index=models.Index(fields=['created_by'], name='qr_checkins_created_7e5fe2_idx'),
        ),
        migrations.AddIndex(
            model_name='qrcheckin',
            index=models.Index(fields=['used_by_student_id'], name='qr_checkins_used_by_068bf5_idx'),
        ),
    ]
