# Generated by Django 5.2.3 on 2025-09-14 08:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0001_initial'),
        ('classes', '0003_alter_classstudent_options_and_more'),
        ('lecturers', '0005_alter_subjectclass_class_id_and_more'),
        ('students', '0008_remove_studentsubject_student_sub_registe_17c846_idx_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='QRCheckinLog',
            fields=[
                ('qr_checkin_log_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('used_at', models.DateTimeField(auto_now_add=True)),
                ('note', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'QR Checkin Log',
                'verbose_name_plural': 'QR Checkin Logs',
                'db_table': 'qr_checkin_logs',
            },
        ),
        migrations.AlterModelOptions(
            name='attendance',
            options={'verbose_name': 'Attendance', 'verbose_name_plural': 'Attendances'},
        ),
        migrations.AlterModelOptions(
            name='attendanceverification',
            options={'verbose_name': 'Attendance Verification', 'verbose_name_plural': 'Attendance Verifications'},
        ),
        migrations.AlterModelOptions(
            name='facerecognitionlog',
            options={'verbose_name': 'Face Recognition Log', 'verbose_name_plural': 'Face Recognition Logs'},
        ),
        migrations.AlterModelOptions(
            name='qrcheckin',
            options={'verbose_name': 'QR Checkin', 'verbose_name_plural': 'QR Checkins'},
        ),
        migrations.RemoveIndex(
            model_name='attendance',
            name='attendances_schedul_438604_idx',
        ),
        migrations.RemoveIndex(
            model_name='attendance',
            name='attendances_student_57d8b0_idx',
        ),
        migrations.RemoveIndex(
            model_name='attendance',
            name='attendances_checkin_8a3486_idx',
        ),
        migrations.RemoveIndex(
            model_name='attendanceverification',
            name='attendance__attenda_d92bd0_idx',
        ),
        migrations.RemoveIndex(
            model_name='attendanceverification',
            name='attendance__lecture_f2bd07_idx',
        ),
        migrations.RemoveIndex(
            model_name='facerecognitionlog',
            name='face_recogn_attenda_8f5bbd_idx',
        ),
        migrations.RemoveIndex(
            model_name='qrcheckin',
            name='qr_checkins_schedul_624ce1_idx',
        ),
        migrations.RemoveIndex(
            model_name='qrcheckin',
            name='qr_checkins_used_by_068bf5_idx',
        ),
        migrations.RenameField(
            model_name='facerecognitionlog',
            old_name='attendace',
            new_name='attendance',
        ),
        migrations.RemoveField(
            model_name='attendance',
            name='checkin_time',
        ),
        migrations.RemoveField(
            model_name='qrcheckin',
            name='used_by_student',
        ),
        migrations.AddField(
            model_name='attendance',
            name='checkin_at',
            field=models.TimeField(null=True),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='attendance_type',
            field=models.CharField(choices=[('F', 'Nhận diện khuôn mặt'), ('Q', 'Quét QR')], max_length=1),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='checkin_device',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='students.device'),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='checkin_lat',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='checkin_long',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='checkin_method',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='face_image_url',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='is_late',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='late_reason',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='note',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='status',
            field=models.CharField(choices=[('P', 'Có mặt'), ('A', 'Vắng'), ('L', 'Đi muộn')], default='P', max_length=1),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='verified_by_ai',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='attendanceverification',
            name='note',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='attendanceverification',
            name='status',
            field=models.CharField(choices=[('P', 'Chờ xác nhận'), ('A', 'Đã xác nhận'), ('R', 'Từ chối')], default='P', max_length=1),
        ),
        migrations.AlterField(
            model_name='facerecognitionlog',
            name='confidence_score',
            field=models.DecimalField(decimal_places=2, max_digits=5),
        ),
        migrations.AlterField(
            model_name='facerecognitionlog',
            name='face_image_url',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='facerecognitionlog',
            name='note',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='facerecognitionlog',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='students.student'),
        ),
        migrations.AlterField(
            model_name='qrcheckin',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='qrcheckin',
            name='latitude',
            field=models.DecimalField(decimal_places=6, max_digits=9),
        ),
        migrations.AlterField(
            model_name='qrcheckin',
            name='longitude',
            field=models.DecimalField(decimal_places=6, max_digits=9),
        ),
        migrations.AlterField(
            model_name='qrcheckin',
            name='max_usage',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='qrcheckin',
            name='qr_code',
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='qrcheckin',
            name='radius',
            field=models.IntegerField(default=50),
        ),
        migrations.AlterField(
            model_name='qrcheckin',
            name='usage_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddIndex(
            model_name='attendance',
            index=models.Index(fields=['schedule', 'student'], name='attendances_schedul_51c919_idx'),
        ),
        migrations.AddIndex(
            model_name='attendance',
            index=models.Index(fields=['checkin_device'], name='attendances_checkin_8a3486_idx'),
        ),
        migrations.AddIndex(
            model_name='attendanceverification',
            index=models.Index(fields=['attendance', 'lecturer'], name='attendance__attenda_2af666_idx'),
        ),
        migrations.AddIndex(
            model_name='facerecognitionlog',
            index=models.Index(fields=['attendance'], name='face_recogn_attenda_09e501_idx'),
        ),
        migrations.AddIndex(
            model_name='qrcheckin',
            index=models.Index(fields=['schedule'], name='qr_checkins_schedul_624ce1_idx'),
        ),
        migrations.AddField(
            model_name='qrcheckinlog',
            name='qr_checkin',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='attendance.qrcheckin'),
        ),
        migrations.AddField(
            model_name='qrcheckinlog',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='students.student'),
        ),
        migrations.AddIndex(
            model_name='qrcheckinlog',
            index=models.Index(fields=['qr_checkin', 'student'], name='qr_checkin__qr_chec_62be93_idx'),
        ),
    ]
